allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  netlify-cli: false
  sharp: false
  unix-dgram: false
  vue-demi: false
minimumReleaseAge: 1440 # 1 day in minutes
saveExact: true
optimisticRepeatInstall: false